### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by scheidan** [sandrinecharles/3-perspectives-calibration#3]
- [ ] change error model to make sure we do not have negative values (logNormal, gamma , truncatedNormal, ...)
- [ ] perspective 1: take data of replicate 1 and make (automatic or by hand) calibration  (use other data as validation)
- [ ] perspective 2: use a all data (as is)
- [ ] perspective 3: use replica 1 as prior and the rest for inference
